### PR TITLE
Added some more patterns

### PR DESCRIPTION
**Pull request by praveer7398**

### CODE REVIEW

**Comment by panditakshay402** [comment]
@praveer7398 read readme.md Before PR

**Comment by praveer7398** [comment]
> @praveer7398 read readme.md Before PR

I don't understand sir , what wrong have i done as its my first time contributing to any open source

**Comment by panditakshay402** [comment]
> > @praveer7398 read readme.md Before PR
> 
> I don't understand sir , what wrong have i done as its my first time contributing to any open source

@praveer7398  Do follow me, star the repo, your PR must have longer contents/code/ do not spam, avoid vulne.

**Comment by praveer7398** [comment]
> > > @praveer7398 read readme.md Before PR
> > 
> > 
> > I don't understand sir , what wrong have i done as its my first time contributing to any open source
> 
> @praveer7398 Do follow me, star the repo, your PR must have longer contents/code/ do not spam, avoid vulne.

Done sir, and those codes are some of the patterns like pascal triangle star patterns diamond star patterns.

**Pull request merged**
