### PR TITLE
Added a binary search code

### PR DESCRIPTION
**Pull request by Aashi19234**
I added a binary search code using recursion. @panditakshay402 
Issue #147 
Screenshot (46)
Screenshot (47)

### CODE REVIEW

**Comment by Aashi19234** [comment]
Please check pr#149

**Comment by Aashi19234** [comment]
Okay will correct it and then issue another pr.

**Comment by panditakshay402** [comment]
In this there is a conflict from ur side check it

**Comment by Aashi19234** [comment]
Ok, I will check.

**Comment by Aashi19234** [comment]
You dont need to merge this pr because you rejected this pr so after that i
issued another pr which was 162 which is showing to me that you have merged
it . Pr 149 and 167 are same i just didn’t star and follow you in pr#149
thats why i issued #167.

**Comment by Aashi19234** [comment]
I have solved the conflict. Please merge pr#149

**Comment by Aashi19234** [comment]
Please review the pr#149 and merge it. @panditakshay402

**Pull request merged**
