### PR TITLE
Create Book Allocation Problem.cpp

### PR DESCRIPTION
**Pull request by PadmeshSharma**

### CODE REVIEW

**Comment by panditakshay402** [comment]
@PadmeshSharma Read and follow the steps of README.MD for PR

**Comment by PadmeshSharma** [comment]
Kindly look into the issue  #191. Now, I have followed all the steps of
Readme.md for PR.

**Comment by PadmeshSharma** [comment]
[image: image.png]
Dear Akshay,

I hope this email finds you well. I am writing to inquire about my
exclusion from Hacktoberfest, even though my pull requests have been
accepted by your project and merged into the main repository.

As an active contributor to your project, I have dedicated a significant
amount of time and effort to improve the codebase and assist in its
development. I was excited to participate in Hacktoberfest this year and
believed that my contributions met the criteria for the event. However, I
recently noticed that I have not received any confirmation or recognition
for my contributions in the context of Hacktoberfest.

I would like to understand the reason behind my exclusion from the event
and whether there might have been any misunderstanding regarding my
contributions. My primary goal is to engage in open source and contribute
meaningfully to projects, and Hacktoberfest has been an excellent way to
promote open-source collaboration. If there are any issues or discrepancies
that I need to address, please let me know so that I can rectify them.

Thank you for your time and consideration. I look forward to your response
and hope to resolve this matter to continue my contributions to the project
and participate in Hacktoberfest.

Best regards,

Padmesh Sharma

**Comment by panditakshay402** [comment]
right now i am getting too much spam PR and after filtration in few days it will be accepted. keep patience!!

**Pull request merged**
