### PR TITLE
fixing the binary search algorithm problem in java folder

### PR DESCRIPTION
**Pull request by AviGawande**
Here in this repo ,in  the searching algorithm in the JAVA sub-folder was not there to work on for the Binary Search Algorithm therefore i contributed that folder by adding the "BinarySearch.java" in the Java Folder.

### CODE REVIEW

**Comment by panditakshay402** [comment]
Read properly readme.md before PR to be accepted

**Comment by panditakshay402** [comment]
Do Follow me and Star the repo to get PR

**Comment by AviGawande** [comment]
i had done PR last night does please verify it or need some changes.

**Comment by AviGawande** [comment]
Does there something i done wrong because lately i checked in the hacktober fest profile it showed that the PR as EXCLUDED what does it means??
Please solve my  problem.

**Comment by panditakshay402** [comment]
ok give me some time.

**Pull request merged**
