### PR TITLE
Binary Search Added

### PR DESCRIPTION
**Pull request by DebarjunChakraborty**
Added Binary Search in java

### CODE REVIEW

**Comment by DebarjunChakraborty** [comment]
Added Doubly linked list too

**Comment by DebarjunChakraborty** [comment]
Pls add label hacktoberfest-accepted as in my profile its showing NOT-PARTICIPATING . Thank you

**Comment by DebarjunChakraborty** [comment]
@panditakshay402 please check if all the necessary changes are made and i have starred this repo and followed you

**Comment by panditakshay402** [comment]
@DebarjunChakraborty Do Follow me and Star the repo to get PR

**Comment by DebarjunChakraborty** [comment]
I did Follow and star your repo

**Pull request merged**
