### PR TITLE
added-mostOptimalBFS

### PR DESCRIPTION
**Pull request by okaydivyansh**
Added cpp code along with explanation

### CODE REVIEW

**Comment by okaydivyansh** [comment]
Please add hacktoberfest label

**Comment by okaydivyansh** [comment]
image

**Comment by panditakshay402** [comment]
> Please add hacktoberfest label

DONE

**Comment by okaydivyansh** [comment]
@panditakshay402  you added hacktoberfest labels but i dont why still, on hacktoberfest site,it says not participating
image

**Comment by panditakshay402** [comment]
> @panditakshay402 you added hacktoberfest labels but i dont why still, on hacktoberfest site, it says not participating image

Now, its updated check and update me !

**Pull request merged**
